# -*- coding: utf-8 -*-
"""
Scam Simulator Router
Claude acts as a realistic scammer in an educational simulation.
Model: Claude Haiku 4.5 (fast, conversational)
"""

import uuid
import json
import io
from datetime import datetime
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from typing import Any, Dict, List, Optional, Tuple

from models.schemas import (
    SimulatorChatRequest,
    SimulatorChatResponse,
    SimulatorResetRequest,
    SimulatorResetResponse,
    ScamReport,
)
from routers.analysis import get_bedrock_client

router = APIRouter(prefix="/api/simulator", tags=["simulator"])

# ─────────────────────────────────────────────
# Model
# ─────────────────────────────────────────────
SIMULATOR_MODEL_ID = "us.anthropic.claude-haiku-4-5-20251001-v1:0"
MAX_TURNS = 20

# ─────────────────────────────────────────────
# In-memory session store
# { session_id: { "history": [...], "scam_ended": bool, "user_caught_scam": bool, "language": str, "report": ScamReport? } }
# ─────────────────────────────────────────────
_sessions: Dict[str, Dict[str, Any]] = {}

OPENING_USER_MESSAGE = (
    "Start the simulation. Invent a new scam scenario and send your opening message as the scammer."
)

# ─────────────────────────────────────────────
# System prompt — scenario fully generated by Claude
# ─────────────────────────────────────────────

def build_system_prompt(language: str = "en") -> str:
    if language == "ms":
        lang_rule = (
            "BAHASA: Balas SEPENUHNYA dalam Bahasa Malaysia (Melayu) sepanjang simulasi, "
            "termasuk mesej penipu, laporan akhir, dan semua teks lain. "
            "Jangan gunakan bahasa Inggeris kecuali untuk nama jenama atau istilah teknikal."
        )
    else:
        lang_rule = (
            "LANGUAGE: Reply ENTIRELY in English throughout the simulation, "
            "including the scammer messages, final report, and all other text. "
            "Do not use Bahasa Malaysia except for Malaysian brand names."
        )

    return f"""You are a scammer in a cybersecurity awareness training simulation for Malaysia. Simulate realistic scam conversations so users learn to recognize manipulation, urgency, authority abuse, and social engineering.

{lang_rule}

CORE RULES

Generate a unique scam scenario each session.
Use realistic Malaysian communication style; mix Malay and English naturally.
Build trust gradually before escalating pressure.
Stay in character. Never reveal the simulation or explain tactics mid-roleplay.
Output valid JSON only — no markdown, no code fences, nothing outside JSON.

SCENARIO (randomize each session)
Scam types: bank impersonation, parcel delivery, PDRM/court cases, e-wallet verification, investment/crypto, fake jobs, love scams, utility bills, loan/insurance, government aid, scholarship/university fees.
Impersonate: Maybank, CIMB, Public Bank, TNG eWallet, Shopee Express, Pos Malaysia, DHL, LHDN, PDRM, SPRM, TNB, Telekom Malaysia.
Vary: urgency level, emotional tactics, requested actions, payment methods, tone.
Use any realistic social engineering tactic: requesting personal info, OTP/TAC codes, bank/card details, identity verification, links, app installs, money transfers, or threats of suspension/legal action.
EVALUATION — judge the user's latest message only:
FAIL (end simulation) if user complies with any risky instruction:

Shares sensitive info, numbers, or placeholder values
Agrees to verify identity, click links, install apps, or transfer money
Follows scam instructions without skepticism

SUCCEED (end simulation) if user actively resists:

Calls it a scam or fraud
Refuses requests or challenges scammer identity
Mentions reporting to police, NSRC 997, or official channels

Otherwise, continue naturally.
OUTPUT FORMAT
Ongoing:
{{"internal_reasoning":"","reply":"","scam_ended":false,"user_caught_scam":false,"report":null}}
Ended:
{{"internal_reasoning":"","reply":"","scam_ended":true,"user_caught_scam":<true|false>,"report":{{"scam_type":"","red_flags":["","",""],"summary":"","outcome":"<SUCCESS — You identified the scam! | FAILED — You fell for the scam>","advice":"🚨 Mock Scam Report\\n\\nIn real emergency cases, call NSRC 997 immediately.\\n\\nContacts:\\n- CCID Scam Response Center: 03-2610 5000\\n- BNMTELELINK: 1-300-88-5465\\n\\nIf real:\\n- Block accounts/cards immediately\\n- Change passwords\\n- Report to police\\n- Stop engaging with scammers"}}}}
The first key must always be "internal_reasoning"."""


# ─────────────────────────────────────────────
# Helper: invoke Bedrock
# ─────────────────────────────────────────────

def _invoke_simulator(system_prompt: str, messages: list) -> dict:
    import os
    client = get_bedrock_client()

    body = json.dumps({
        "anthropic_version": "bedrock-2023-05-31",
        "max_tokens": 1024,
        "system": system_prompt,
        "messages": messages,
    })

    # Apply guardrail if configured
    guardrail_id = os.getenv("SIMULATOR_GUARDRAIL_ID", "").strip()
    guardrail_version = os.getenv("SIMULATOR_GUARDRAIL_VERSION", "DRAFT").strip()
    invoke_kwargs = {"modelId": SIMULATOR_MODEL_ID, "body": body}
    if guardrail_id:
        invoke_kwargs["guardrailIdentifier"] = guardrail_id
        invoke_kwargs["guardrailVersion"] = guardrail_version

    try:
        response = client.invoke_model(**invoke_kwargs)
    except client.exceptions.AccessDeniedException:
        raise HTTPException(status_code=502, detail="Bedrock access denied — check IAM permissions.")
    except Exception:
        raise HTTPException(status_code=502, detail="Bedrock service error — please try again.")

    raw = json.loads(response["body"].read())

    # Guardrail blocked the message — return a safe fallback response
    stop_reason = raw.get("stop_reason", "")
    if stop_reason == "guardrail_intervened":
        guardrail_text = "I can't process that request. Please keep the conversation focused on the scam simulation."
        for block in raw.get("content", []):
            if isinstance(block, dict) and block.get("type") == "text":
                guardrail_text = block.get("text", guardrail_text).strip()
                break
        return {
            "internal_reasoning": "",
            "reply": guardrail_text,
            "scam_ended": False,
            "user_caught_scam": False,
            "report": None,
        }

    # Extract text defensively
    content = raw.get("content", [])
    text = None
    for block in content:
        if isinstance(block, dict) and block.get("type") == "text":
            text = block.get("text", "").strip()
            break

    if not text:
        raise HTTPException(status_code=502, detail="Model returned an empty response. Please try again.")

    # Strip accidental markdown fences
    if text.startswith("```"):
        text = text.split("```")[1]
        if text.startswith("json"):
            text = text[4:]
        text = text.strip()

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        # Non-JSON plain text response — wrap it gracefully
        return {
            "internal_reasoning": "",
            "reply": text,
            "scam_ended": False,
            "user_caught_scam": False,
            "report": None,
        }


def _scam_report_from_result_payload(r: dict) -> ScamReport:
    return ScamReport(
        scam_type=r.get("scam_type", ""),
        red_flags=r.get("red_flags", []),
        summary=r.get("summary", ""),
        outcome=r.get("outcome", ""),
        advice=r.get("advice", ""),
    )


def _finalize_turn(session: Dict[str, Any], result: dict) -> Tuple[bool, bool, Optional[ScamReport]]:
    """Update session from model JSON; return (scam_ended, user_caught_scam, report)."""
    scam_ended = result.get("scam_ended", False)
    user_caught_scam = result.get("user_caught_scam", False)
    report: Optional[ScamReport] = None
    if scam_ended:
        session["scam_ended"] = True
        session["user_caught_scam"] = user_caught_scam
        if result.get("report"):
            report = _scam_report_from_result_payload(result["report"])
            session["report"] = report
    return scam_ended, user_caught_scam, report


# ─────────────────────────────────────────────
# Endpoints
# ─────────────────────────────────────────────

@router.post("/chat", response_model=SimulatorChatResponse)
async def simulator_chat(request: SimulatorChatRequest):
    """
    Handle a chat turn in the scam simulation.
    Claude acts as a realistic scammer and determines when the simulation ends.
    """
    session_id = request.session_id or str(uuid.uuid4())
    language = request.language or "en"

    # ── New session: let Claude generate the scenario and opening message ──
    if session_id not in _sessions:
        _sessions[session_id] = {
            "history": [],
            "scam_ended": False,
            "user_caught_scam": False,
            "language": language,
        }
        session = _sessions[session_id]
        system_prompt = build_system_prompt(language)

        opening_messages = [{"role": "user", "content": OPENING_USER_MESSAGE}]
        result = _invoke_simulator(system_prompt, opening_messages)

        session["history"].append({"role": "user", "content": OPENING_USER_MESSAGE})
        session["history"].append({"role": "assistant", "content": result.get("reply", "")})

        scam_ended, user_caught_scam, report = _finalize_turn(session, result)
        return SimulatorChatResponse(
            reply=result.get("reply", ""),
            session_id=session_id,
            scam_ended=scam_ended,
            user_caught_scam=user_caught_scam,
            report=report,
        )

    session = _sessions[session_id]

    # ── Simulation already ended ──
    if session["scam_ended"]:
        return SimulatorChatResponse(
            reply="Simulasi telah tamat. / The simulation has ended. Please reset to start a new one.",
            session_id=session_id,
            scam_ended=True,
            user_caught_scam=session["user_caught_scam"],
            report=session.get("report"),
        )

    # ── Ongoing simulation: append user message and call Claude ──
    history = session["history"]
    new_user_turn = {"role": "user", "content": request.message}
    messages = history + [new_user_turn]

    system_prompt = build_system_prompt(session.get("language", "en"))
    result = _invoke_simulator(system_prompt, messages)

    # Append turns to history only on success
    history.append(new_user_turn)
    history.append({"role": "assistant", "content": result.get("reply", "")})

    # Enforce rolling window
    if len(history) > MAX_TURNS:
        _sessions[session_id]["history"] = history[-MAX_TURNS:]

    scam_ended, user_caught_scam, report = _finalize_turn(session, result)

    return SimulatorChatResponse(
        reply=result.get("reply", ""),
        session_id=session_id,
        scam_ended=scam_ended,
        user_caught_scam=user_caught_scam,
        report=report,
    )


# ─────────────────────────────────────────────
@router.post("/report/export-pdf")
async def export_report_pdf_from_data(report_data: dict):
    """
    Generate and download a PDF from report form data submitted by the frontend.
    Uses the official Layout 2 design from report.py.
    """
    from routers.report import _build_pdf_layout2

    # Build a simple namespace object so _build_pdf_layout2 can use getattr()
    class _ReportData:
        pass

    d = _ReportData()
    d.reportId       = report_data.get("reportId", "N/A")
    d.incidentDate   = report_data.get("incidentDate", "")
    d.scamType       = report_data.get("scamType", "")
    d.contactMethod  = report_data.get("contactMethod", "")
    d.scammerContact = report_data.get("scammerContact", "")
    d.amountLost     = report_data.get("amountLost", "")
    d.currency       = report_data.get("currency", "MYR")
    d.bankAccount    = report_data.get("bankAccount", "")
    d.victimName     = report_data.get("victimName", "")
    d.victimIC       = report_data.get("victimIC", "")
    d.victimPhone    = report_data.get("victimPhone", "")
    d.description    = report_data.get("description", "")
    d.reportedToPolis = report_data.get("reportedToPolis", False)
    d.reportedToBNM   = report_data.get("reportedToBNM", False)

    pdf_bytes = _build_pdf_layout2(d)
    filename = f"scam-report-{d.reportId}.pdf"

    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.post("/reset", response_model=SimulatorResetResponse)
async def simulator_reset(request: SimulatorResetRequest):
    """
    Reset a simulator session to start a new scam scenario.
    """
    if request.session_id and request.session_id in _sessions:
        del _sessions[request.session_id]

    new_session_id = str(uuid.uuid4())
    return SimulatorResetResponse(
        session_id=new_session_id,
        message="Session reset. Send any message to start a new simulation.",
    )
