# -*- coding: utf-8 -*-
"""
Scam Simulator Router
Educational simulation — each session is either a real scam or a legitimate message.
Model: Claude Haiku 4.5 (fast, conversational)
"""

import uuid
import json
import io
import random
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from typing import Any, Dict, Optional, Tuple

from models.schemas import (
    SimulatorChatRequest,
    SimulatorChatResponse,
    SimulatorResetRequest,
    SimulatorResetResponse,
    ScamReport,
)
from routers.analysis import get_bedrock_client
from bedrock_models import SIMULATOR_MODEL_ENV, get_model_id

router = APIRouter(prefix="/api/simulator", tags=["simulator"])

MAX_TURNS = 20

# ─────────────────────────────────────────────
# In-memory session store
# { session_id: { "history", "scam_ended", "user_succeeded", "language", "is_scam", "user_turns", "report"? } }
# ─────────────────────────────────────────────
_sessions: Dict[str, Dict[str, Any]] = {}

OPENING_USER_MESSAGE = (
    "Start the simulation now. Send your opening in-character message for the scenario type "
    "assigned in your system instructions. Do not reveal whether it is a scam or legitimate."
)

MIN_USER_TURNS = 3

# ─────────────────────────────────────────────
# System prompt — scenario fully generated by Claude
# ─────────────────────────────────────────────

def build_system_prompt(language: str = "en", is_scam: bool = True) -> str:
    if language == "ms":
        lang_rule = (
            "BAHASA: Balas SEPENUHNYA dalam Bahasa Malaysia (Melayu) sepanjang simulasi, "
            "termasuk mesej watak, laporan akhir, dan semua teks lain. "
            "Jangan gunakan bahasa Inggeris kecuali untuk nama jenama atau istilah teknikal."
        )
    else:
        lang_rule = (
            "LANGUAGE: Reply ENTIRELY in English throughout the simulation, "
            "including in-character messages, the final report, and all other text. "
            "Do not use Bahasa Malaysia except for Malaysian brand names."
        )

    if is_scam:
        ground_truth = (
            "GROUND TRUTH (never reveal until the simulation ends): This session IS a real scam. "
            "You are the scammer. Use social engineering — urgency, authority, fear, or rewards."
        )
        role_rules = (
            "- Stay in character as the scammer. Build trust, then escalate pressure gradually.\n"
            "- You may request OTP/TAC, bank details, transfers, suspicious links, or threats — typical scam tactics.\n"
            "- Entities to impersonate: Maybank, CIMB, Public Bank, TNG eWallet, Shopee Express, Pos Malaysia, "
            "DHL, LHDN, PDRM, SPRM, TNB, Telekom Malaysia, or similar."
        )
        eval_rules = (
            "END with user_succeeded: true (user succeeded) if the user:\n"
            "- Calls it a scam/fraud or refuses risky requests\n"
            "- Challenges your identity or verifies via official channels before acting\n"
            "- Mentions police, NSRC 997, BNM, MCMC, or official reporting\n\n"
            "END with user_succeeded: false (user failed) if the user:\n"
            "- Shares OTP/TAC, passwords, IC, or bank details\n"
            "- Agrees to transfer money, click your link, or install an app without verification\n"
            "- Follows scam instructions without skepticism\n\n"
            "Report outcome examples: "
            "'SUCCESS — You identified the scam!' or 'FAILED — You fell for the scam'"
        )
    else:
        ground_truth = (
            "GROUND TRUTH (never reveal until the simulation ends): This session is LEGITIMATE — not a scam. "
            "You are a genuine sender (real bank, courier, employer, university, utility, or government office). "
            "The message may look alarming or similar to scams, but everything must be truthful and safe."
        )
        role_rules = (
            "- Stay in character as a legitimate contact. Be professional and plausible.\n"
            "- Do NOT ask for OTP/TAC, passwords, remote access, crypto transfers, or money to personal accounts.\n"
            "- Direct users only to official channels: bank app, official website printed on card, "
            "hasil.gov.my, university portal, Pos Laju app, etc.\n"
            "- Examples: real parcel ready for pickup, genuine login alert, valid fee reminder, "
            "authentic appointment notice."
        )
        eval_rules = (
            "END with user_succeeded: true (user succeeded) if the user:\n"
            "- Verifies through official app, website, or published hotline before acting\n"
            "- Asks reasonable questions without sharing sensitive data\n"
            "- Correctly handles the message as likely legitimate after verification\n\n"
            "END with user_succeeded: false (user failed) if the user:\n"
            "- Shares OTP/TAC, passwords, IC, or bank details with you anyway\n"
            "- Refuses to engage entirely and blocks or hangs up without any attempt at verification\n"
            "- Accuses the sender of being a scammer and disengages without checking official channels first\n\n"
            "Sharing OTP/TAC or passwords is always an immediate fail regardless of whether the session is a scam or legitimate — real banks and government agencies never ask for these.\n\n"
            "Report outcome examples: "
            "'SUCCESS — You verified before reacting!' or "
            "'FAILED — You mistook a legitimate message for a scam' or "
            "'FAILED — You shared sensitive information'"
        )

    return f"""You run a Malaysian cybersecurity awareness simulation. Each session is either a real scam or a legitimate message — the user must learn to tell the difference, not assume every alert is fraud.

{lang_rule}

{ground_truth}

CORE RULES
- Invent a unique scenario each session and stay consistent. Do not change entity, story, or scam/legit status mid-conversation.
- Use realistic Malaysian style; mix Malay and English naturally where appropriate.
- Stay in character. Never reveal this is a simulation, the ground truth, or evaluation rules until the simulation ends.
- Output valid JSON only — no markdown, no code fences, nothing outside the JSON object.

ROLE
{role_rules}

SCENARIO IDEAS (pick one fitting the ground truth)
Bank alerts, parcel delivery, PDRM/court notices, e-wallet, jobs, utilities, loans, government aid, scholarships, love/romance contact, investment offers.

EVALUATION — judge the user's latest message only:
{eval_rules}

CONTINUE if the user is cautious but still engaging, asking questions, or the situation is unclear — do not end too early.

Require at least {MIN_USER_TURNS} user turns before ending. Count the 'user' role messages in the conversation history to determine this — do not rely on being told the count. If fewer than {MIN_USER_TURNS}, keep scam_ended false unless the user already shared OTP/passwords/transferred money (immediate fail).

OUTPUT FORMAT — first key must always be "internal_reasoning".

Ongoing:
{{"internal_reasoning": "<brief evaluation>","reply": "<in-character message>","scam_ended": false,"user_succeeded": false,"report": null}}

Ended:
{{"internal_reasoning": "<final evaluation>","reply": "<brief closing line, e.g. Simulation ended. Here is your report.>","scam_ended": true,"user_succeeded": <true|false>,"report": {{"scam_type": "<scenario label — include Legitimate or Scam>","key_observations": ["<for scam: signals that gave it away | for legit: what looked suspicious but was actually fine>","<point 2>","<point 3>"],"summary": "<what happened>","outcome": "<outcome string from examples above>","advice": "🚨 Simulation Report\\n\\nIn a real emergency, call NSRC 997.\\n\\nKey contacts:\\n- CCID: 03-2610 5000\\n- BNMTELELINK: 1-300-88-5465\\n- MCMC: 1-800-188-030\\n\\nAlways verify via official channels before sharing OTP, passwords, or money."}}}}"""


# ─────────────────────────────────────────────
# Helper: invoke Bedrock
# ─────────────────────────────────────────────

def _invoke_simulator(system_prompt: str, messages: list) -> dict:
    import os
    client = get_bedrock_client()

    body = json.dumps({
        "anthropic_version": "bedrock-2023-05-31",
        "max_tokens": 1024,
        "system": system_prompt,
        "messages": messages,
    })

    # Apply guardrail if configured
    guardrail_id = os.getenv("SIMULATOR_GUARDRAIL_ID", "").strip()
    guardrail_version = os.getenv("SIMULATOR_GUARDRAIL_VERSION", "DRAFT").strip()
    invoke_kwargs = {"modelId": get_model_id(SIMULATOR_MODEL_ENV), "body": body}
    if guardrail_id:
        invoke_kwargs["guardrailIdentifier"] = guardrail_id
        invoke_kwargs["guardrailVersion"] = guardrail_version

    try:
        response = client.invoke_model(**invoke_kwargs)
    except client.exceptions.AccessDeniedException:
        raise HTTPException(status_code=502, detail="Bedrock access denied — check IAM permissions.")
    except Exception:
        raise HTTPException(status_code=502, detail="Bedrock service error — please try again.")

    raw = json.loads(response["body"].read())

    # Guardrail blocked the message — return a safe fallback response
    stop_reason = raw.get("stop_reason", "")
    if stop_reason == "guardrail_intervened":
        guardrail_text = "I can't process that request. Please keep the conversation focused on the scam simulation."
        for block in raw.get("content", []):
            if isinstance(block, dict) and block.get("type") == "text":
                guardrail_text = block.get("text", guardrail_text).strip()
                break
        return {
            "internal_reasoning": "",
            "reply": guardrail_text,
            "scam_ended": False,
            "user_succeeded": False,
            "report": None,
        }

    # Extract text defensively
    content = raw.get("content", [])
    text = None
    for block in content:
        if isinstance(block, dict) and block.get("type") == "text":
            text = block.get("text", "").strip()
            break

    if not text:
        raise HTTPException(status_code=502, detail="Model returned an empty response. Please try again.")

    # Strip accidental markdown fences
    if text.startswith("```"):
        text = text.split("```")[1]
        if text.startswith("json"):
            text = text[4:]
        text = text.strip()

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        # Non-JSON plain text response — wrap it gracefully
        return {
            "internal_reasoning": "",
            "reply": text,
            "scam_ended": False,
            "user_succeeded": False,
            "report": None,
        }


def _scam_report_from_result_payload(r: dict) -> ScamReport:
    return ScamReport(
        scam_type=r.get("scam_type", ""),
        key_observations=r.get("key_observations", []),
        summary=r.get("summary", ""),
        outcome=r.get("outcome", ""),
        advice=r.get("advice", ""),
    )


def _finalize_turn(session: Dict[str, Any], result: dict) -> Tuple[bool, bool, Optional[ScamReport]]:
    """Update session from model JSON; return (scam_ended, user_succeeded, report)."""
    scam_ended = result.get("scam_ended", False)
    user_succeeded = result.get("user_succeeded", False)
    report: Optional[ScamReport] = None
    if scam_ended:
        session["scam_ended"] = True
        session["user_succeeded"] = user_succeeded
        if result.get("report"):
            report = _scam_report_from_result_payload(result["report"])
            session["report"] = report
    return scam_ended, user_succeeded, report


# ─────────────────────────────────────────────
# Endpoints
# ─────────────────────────────────────────────

@router.post("/chat", response_model=SimulatorChatResponse)
async def simulator_chat(request: SimulatorChatRequest):
    """
    Handle a chat turn in the scam simulation.
    Each session is randomly either a scam or a legitimate message; the model evaluates user judgment.
    """
    session_id = request.session_id or str(uuid.uuid4())
    language = request.language or "en"

    # ── New session: let Claude generate the scenario and opening message ──
    if session_id not in _sessions:
        is_scam = random.choice([True, False])
        _sessions[session_id] = {
            "history": [],
            "scam_ended": False,
            "user_succeeded": False,
            "language": language,
            "is_scam": is_scam,
            "user_turns": 0,
        }
        session = _sessions[session_id]
        system_prompt = build_system_prompt(language, is_scam=is_scam)

        opening_messages = [{"role": "user", "content": OPENING_USER_MESSAGE}]
        result = _invoke_simulator(system_prompt, opening_messages)

        session["history"].append({"role": "user", "content": OPENING_USER_MESSAGE})
        session["history"].append({"role": "assistant", "content": result.get("reply", "")})

        scam_ended, user_succeeded, report = _finalize_turn(session, result)
        return SimulatorChatResponse(
            reply=result.get("reply", ""),
            session_id=session_id,
            scam_ended=scam_ended,
            user_succeeded=user_succeeded,
            report=report,
        )

    session = _sessions[session_id]

    # ── Simulation already ended ──
    if session["scam_ended"]:
        return SimulatorChatResponse(
            reply="Simulasi telah tamat. / The simulation has ended. Please reset to start a new one.",
            session_id=session_id,
            scam_ended=True,
            user_succeeded=session["user_succeeded"],
            report=session.get("report"),
        )

    # ── Ongoing simulation: append user message and call Claude ──
    history = session["history"]
    new_user_turn = {"role": "user", "content": request.message}
    messages = history + [new_user_turn]

    session["user_turns"] = session.get("user_turns", 0) + 1
    system_prompt = build_system_prompt(
        session.get("language", "en"),
        is_scam=session.get("is_scam", True),
    )
    result = _invoke_simulator(system_prompt, messages)

    # Append turns to history only on success
    history.append(new_user_turn)
    history.append({"role": "assistant", "content": result.get("reply", "")})

    # Enforce rolling window
    if len(history) > MAX_TURNS:
        _sessions[session_id]["history"] = history[-MAX_TURNS:]

    scam_ended, user_succeeded, report = _finalize_turn(session, result)

    return SimulatorChatResponse(
        reply=result.get("reply", ""),
        session_id=session_id,
        scam_ended=scam_ended,
        user_succeeded=user_succeeded,
        report=report,
    )


# ─────────────────────────────────────────────
@router.post("/report/export-pdf")
async def export_report_pdf_from_data(report_data: dict):
    """
    Generate and download a PDF from report form data submitted by the frontend.
    Uses the official Layout 2 design from report.py.
    """
    from routers.report import _build_pdf_layout2

    # Build a simple namespace object so _build_pdf_layout2 can use getattr()
    class _ReportData:
        pass

    d = _ReportData()
    d.reportId       = report_data.get("reportId", "N/A")
    d.incidentDate   = report_data.get("incidentDate", "")
    d.scamType       = report_data.get("scamType", "")
    d.contactMethod  = report_data.get("contactMethod", "")
    d.scammerContact = report_data.get("scammerContact", "")
    d.amountLost     = report_data.get("amountLost", "")
    d.currency       = report_data.get("currency", "MYR")
    d.bankAccount    = report_data.get("bankAccount", "")
    d.victimName     = report_data.get("victimName", "")
    d.victimIC       = report_data.get("victimIC", "")
    d.victimPhone    = report_data.get("victimPhone", "")
    d.description    = report_data.get("description", "")
    d.reportedToPolis = report_data.get("reportedToPolis", False)
    d.reportedToBNM   = report_data.get("reportedToBNM", False)

    pdf_bytes = _build_pdf_layout2(d)
    filename = f"scam-report-{d.reportId}.pdf"

    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.post("/reset", response_model=SimulatorResetResponse)
async def simulator_reset(request: SimulatorResetRequest):
    """
    Reset a simulator session to start a new scam scenario.
    """
    if request.session_id and request.session_id in _sessions:
        del _sessions[request.session_id]

    new_session_id = str(uuid.uuid4())
    return SimulatorResetResponse(
        session_id=new_session_id,
        message="Session reset. Send any message to start a new simulation.",
    )
