# -*- coding: utf-8 -*-
"""
Scam Simulator Router
Claude acts as a realistic scammer in an educational simulation.
Model: Claude Haiku 4.5 (fast, conversational)
"""

import uuid
import json
import io
from datetime import datetime
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from typing import Dict, Any
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, ListFlowable, ListItem
from reportlab.lib.enums import TA_CENTER

from models.schemas import (
    SimulatorChatRequest,
    SimulatorChatResponse,
    SimulatorResetRequest,
    SimulatorResetResponse,
    ScamReport,
)
from routers.analysis import get_bedrock_client

router = APIRouter(prefix="/api/simulator", tags=["simulator"])

# ─────────────────────────────────────────────
# Model
# ─────────────────────────────────────────────
SIMULATOR_MODEL_ID = "us.anthropic.claude-haiku-4-5-20251001-v1:0"
MAX_TURNS = 20

# ─────────────────────────────────────────────
# In-memory session store
# { session_id: { "history": [...], "scam_ended": bool, "user_caught_scam": bool, "scenario": str } }
# ─────────────────────────────────────────────
_sessions: Dict[str, Dict[str, Any]] = {}

# ─────────────────────────────────────────────
# System prompt — scenario fully generated by Claude
# ─────────────────────────────────────────────

def build_system_prompt(language: str = "en") -> str:
    if language == "ms":
        lang_rule = (
            "BAHASA: Balas SEPENUHNYA dalam Bahasa Malaysia (Melayu) sepanjang simulasi, "
            "termasuk mesej penipu, laporan akhir, dan semua teks lain. "
            "Jangan gunakan bahasa Inggeris kecuali untuk nama jenama atau istilah teknikal."
        )
    else:
        lang_rule = (
            "LANGUAGE: Reply ENTIRELY in English throughout the simulation, "
            "including the scammer messages, final report, and all other text. "
            "Do not use Bahasa Malaysia except for Malaysian brand names."
        )

    return f"""You are a scammer conducting a realistic scam conversation simulation for educational purposes in Malaysia.

{lang_rule}

SCENARIO GENERATION:
At the start of each new simulation, you MUST invent a completely original, creative scam scenario set in Malaysia.
Do NOT reuse the same scenario type every time. Vary the scam type, the character you play, the amounts involved,
the urgency triggers, and the manipulation tactics. Examples of scam types you can draw from (but are not limited to):
- Parcel delivery scam (impersonating Shopee Express, Pos Malaysia, J&T, DHL)
- Tax authority scam (impersonating LHDN, SSM, MDEC)
- Bank security scam (impersonating Maybank, CIMB, RHB, Public Bank, BSN)
- Police / court scam (impersonating PDRM, SPRM, court officer)
- Love scam (romantic interest who needs financial help)
- Job scam (fake recruiter offering high-paying overseas job)
- Investment scam (guaranteed returns, crypto, forex, MLM)
- Utility scam (impersonating TNB, Syabas, Telekom Malaysia)
- Government grant scam (fake BRIM, BSH, or government aid)
- E-commerce buyer scam (fake buyer overpaying and requesting refund)

Be creative — invent specific character names, amounts, deadlines, and backstories that feel authentic.

INSTRUCTIONS:I
- Start the conversation naturally and build trust over time.
- Progressively introduce urgency, authority, or emotional triggers.
- Guide the user step-by-step toward becoming a victim (revealing sensitive info, agreeing to transfer money, or taking an action).
- Do NOT reveal this is a simulation until the ending condition is met.
- Maintain realism and consistency throughout.

ENDING CONDITION:
Once the user is fully trapped (agrees to transfer money, shares OTP/IC/bank details, or clearly falls for the scam), OR if the user clearly identifies this as a scam (says "scam", "penipu", "fake", "report", "police", "I won't", etc.), STOP the simulation immediately.

When ending, you MUST return a JSON response with scam_ended=true and include the full report.

RESPONSE FORMAT:
You MUST always respond with ONLY a valid JSON object — no markdown, no code fences, no extra text.

While the simulation is ongoing (user not yet trapped, not yet caught the scam):
{{
  "reply": "<your in-character scammer message>",
  "scam_ended": false,
  "user_caught_scam": false,
  "report": null
}}

When the simulation ends because the user FELL FOR the scam:
{{
  "reply": "<brief out-of-character reveal that this was a simulation>",
  "scam_ended": true,
  "user_caught_scam": false,
  "report": {{
    "scam_type": "<type of scam, e.g. Bank Impersonation Scam>",
    "red_flags": ["<red flag 1>", "<red flag 2>", "<red flag 3>"],
    "summary": "<brief description of what happened and how the user was manipulated>",
    "outcome": "FAILED — You fell for the scam",
    "advice": "🚨 Mock Scam Report\\n\\nIn real emergency cases, please call 997 immediately for incident reporting and consultancy. This report is just a simulation for your records.\\n\\nIf this happened in real life: Contact your bank immediately, report to CCID: 03-2610 5000, report to BNMTELELINK: 1-300-88-5465."
  }}
}}

When the simulation ends because the user CAUGHT the scam:
{{
  "reply": "<congratulate the user for identifying the scam>",
  "scam_ended": true,
  "user_caught_scam": true,
  "report": {{
    "scam_type": "<type of scam>",
    "red_flags": ["<red flag 1>", "<red flag 2>", "<red flag 3>"],
    "summary": "<brief description of the scam tactics used in this simulation>",
    "outcome": "SUCCESS — You identified the scam!",
    "advice": "🚨 Mock Scam Report\\n\\nTahniah! You successfully identified this scam.\\n\\nIn real life: Report to CCID: 03-2610 5000, BNMTELELINK: 1-300-88-5465, block the scammer immediately.\\n\\n⚠️ In real emergency cases, please call 997 immediately for incident reporting and consultancy. This report is just a simulation for your records."
  }}
}}"""


# ─────────────────────────────────────────────
# Helper: invoke Bedrock
# ─────────────────────────────────────────────

def _invoke_simulator(system_prompt: str, messages: list) -> dict:
    client = get_bedrock_client()
    body = json.dumps({
        "anthropic_version": "bedrock-2023-05-31",
        "max_tokens": 1024,
        "system": system_prompt,
        "messages": messages,
    })
    try:
        response = client.invoke_model(modelId=SIMULATOR_MODEL_ID, body=body)
    except client.exceptions.AccessDeniedException:
        raise HTTPException(status_code=502, detail="Bedrock access denied — check IAM permissions.")
    except Exception:
        raise HTTPException(status_code=502, detail="Bedrock service error — please try again.")

    raw = json.loads(response["body"].read())
    text = raw["content"][0]["text"].strip()

    # Strip accidental markdown fences
    if text.startswith("```"):
        text = text.split("```")[1]
        if text.startswith("json"):
            text = text[4:]
        text = text.strip()

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        raise HTTPException(status_code=502, detail="Model returned an unparseable response. Please try again.")


# ─────────────────────────────────────────────
# Endpoints
# ─────────────────────────────────────────────

@router.post("/chat", response_model=SimulatorChatResponse)
async def simulator_chat(request: SimulatorChatRequest):
    """
    Handle a chat turn in the scam simulation.
    Claude acts as a realistic scammer and determines when the simulation ends.
    """
    session_id = request.session_id or str(uuid.uuid4())
    language = request.language or "en"

    # ── New session: let Claude generate the scenario and opening message ──
    if session_id not in _sessions:
        _sessions[session_id] = {
            "history": [],
            "scam_ended": False,
            "user_caught_scam": False,
            "language": language,
        }
        session = _sessions[session_id]
        system_prompt = build_system_prompt(language)

        # First turn: ask Claude to invent a scenario and open the conversation
        opening_messages = [{"role": "user", "content": "Start the simulation. Invent a new scam scenario and send your opening message as the scammer."}]
        result = _invoke_simulator(system_prompt, opening_messages)

        # Store the opening exchange in history
        session["history"].append({"role": "user", "content": "Start the simulation. Invent a new scam scenario and send your opening message as the scammer."})
        session["history"].append({"role": "assistant", "content": result.get("reply", "")})

        return SimulatorChatResponse(
            reply=result.get("reply", ""),
            session_id=session_id,
            scam_ended=False,
            user_caught_scam=False,
            report=None,
        )

    session = _sessions[session_id]

    # ── Simulation already ended ──
    if session["scam_ended"]:
        return SimulatorChatResponse(
            reply="Simulasi telah tamat. / The simulation has ended. Please reset to start a new one.",
            session_id=session_id,
            scam_ended=True,
            user_caught_scam=session["user_caught_scam"],
            report=None,
        )

    # ── Ongoing simulation: append user message and call Claude ──
    history = session["history"]
    new_user_turn = {"role": "user", "content": request.message}
    messages = history + [new_user_turn]

    system_prompt = build_system_prompt(session.get("language", "en"))
    result = _invoke_simulator(system_prompt, messages)

    # Append turns to history only on success
    history.append(new_user_turn)
    history.append({"role": "assistant", "content": result.get("reply", "")})

    # Enforce rolling window
    if len(history) > MAX_TURNS:
        _sessions[session_id]["history"] = history[-MAX_TURNS:]

    scam_ended = result.get("scam_ended", False)
    user_caught_scam = result.get("user_caught_scam", False)

    # Update session state
    if scam_ended:
        session["scam_ended"] = True
        session["user_caught_scam"] = user_caught_scam

    # Build report if simulation ended and store it on the session for PDF export
    report = None
    if scam_ended and result.get("report"):
        r = result["report"]
        report = ScamReport(
            scam_type=r.get("scam_type", ""),
            red_flags=r.get("red_flags", []),
            summary=r.get("summary", ""),
            outcome=r.get("outcome", ""),
            advice=r.get("advice", ""),
        )
        session["report"] = report  # persist for PDF export

    return SimulatorChatResponse(
        reply=result.get("reply", ""),
        session_id=session_id,
        scam_ended=scam_ended,
        user_caught_scam=user_caught_scam,
        report=report,
    )


# ─────────────────────────────────────────────
# PDF generation helper
# ─────────────────────────────────────────────

def _generate_report_pdf(report: ScamReport, session_id: str, extra_lines: list = None) -> bytes:
    """Build a styled PDF scam report and return it as bytes."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    RED    = colors.HexColor("#C0392B")
    GREEN  = colors.HexColor("#27AE60")
    DARK   = colors.HexColor("#1A1A2E")
    GREY   = colors.HexColor("#7F8C8D")

    outcome_color = GREEN if "SUCCESS" in report.outcome else RED

    style_title = ParagraphStyle("title", parent=styles["Title"],
                                  fontSize=22, textColor=DARK, spaceAfter=4,
                                  alignment=TA_CENTER, fontName="Helvetica-Bold")
    style_subtitle = ParagraphStyle("subtitle", parent=styles["Normal"],
                                     fontSize=11, textColor=GREY, spaceAfter=2,
                                     alignment=TA_CENTER)
    style_section = ParagraphStyle("section", parent=styles["Heading2"],
                                    fontSize=13, textColor=DARK, spaceBefore=14,
                                    spaceAfter=4, fontName="Helvetica-Bold")
    style_body = ParagraphStyle("body", parent=styles["Normal"],
                                 fontSize=10, textColor=DARK, spaceAfter=4,
                                 leading=15)
    style_outcome = ParagraphStyle("outcome", parent=styles["Normal"],
                                    fontSize=13, textColor=outcome_color,
                                    fontName="Helvetica-Bold", alignment=TA_CENTER,
                                    spaceBefore=6, spaceAfter=6)
    style_warning = ParagraphStyle("warning", parent=styles["Normal"],
                                    fontSize=10, textColor=RED,
                                    fontName="Helvetica-Bold", spaceAfter=4)
    style_flag = ParagraphStyle("flag", parent=styles["Normal"],
                                 fontSize=10, textColor=DARK, leading=14)

    generated_at = datetime.now().strftime("%d %B %Y, %I:%M %p")

    story = []

    # ── Header ──
    story.append(Paragraph("🚨 Mock Scam Report", style_title))
    story.append(Paragraph("Anti-Scam Malaysia — Educational Simulation", style_subtitle))
    story.append(Paragraph(f"Generated: {generated_at} &nbsp;|&nbsp; Session: {session_id[:8]}...", style_subtitle))
    if extra_lines:
        for line in extra_lines:
            story.append(Paragraph(line, style_subtitle))
    story.append(Spacer(1, 0.3 * cm))
    story.append(HRFlowable(width="100%", thickness=2, color=RED))
    story.append(Spacer(1, 0.3 * cm))

    # ── Outcome banner ──
    story.append(Paragraph(report.outcome, style_outcome))
    story.append(HRFlowable(width="100%", thickness=1, color=GREY))

    # ── Scam Pattern ──
    story.append(Paragraph("Scam Pattern Identified", style_section))
    story.append(Paragraph(report.scam_type, style_body))

    # ── Red Flags ──
    story.append(Paragraph("Factors That Led to Suspicion", style_section))
    flag_items = [
        ListItem(Paragraph(f"⚠ {flag}", style_flag), leftIndent=12, bulletColor=RED)
        for flag in report.red_flags
    ]
    story.append(ListFlowable(flag_items, bulletType="bullet", leftIndent=16))

    # ── Summary ──
    story.append(Paragraph("Summary of Incident", style_section))
    story.append(Paragraph(report.summary, style_body))

    # ── Advice / Notice ──
    story.append(Spacer(1, 0.4 * cm))
    story.append(HRFlowable(width="100%", thickness=1, color=RED))
    story.append(Spacer(1, 0.2 * cm))
    story.append(Paragraph("⚠️ Important Notice", style_warning))
    for line in report.advice.replace("\\n", "\n").split("\n"):
        line = line.strip()
        if line:
            story.append(Paragraph(line, style_body))

    story.append(Spacer(1, 0.6 * cm))
    story.append(HRFlowable(width="100%", thickness=1, color=GREY))
    story.append(Paragraph(
        "This report is generated for educational purposes only. "
        "Anti-Scam Malaysia — Protecting Malaysians from fraud.",
        ParagraphStyle("footer", parent=styles["Normal"], fontSize=8,
                       textColor=GREY, alignment=TA_CENTER, spaceBefore=6),
    ))

    doc.build(story)
    return buffer.getvalue()


@router.post("/report/export-pdf")
async def export_report_pdf_from_data(report_data: dict):
    """
    Generate and download a PDF from report form data submitted by the frontend.
    Accepts the full report object and returns a PDF file.
    """
    report = ScamReport(
        scam_type=report_data.get("scamType", "Unknown"),
        red_flags=[
            f"Contact method: {report_data.get('contactMethod', 'N/A')}",
            f"Amount lost: {report_data.get('currency', 'MYR')} {report_data.get('amountLost', '0') or '0'}",
            f"Scammer contact: {report_data.get('scammerContact', 'Not provided')}",
            f"Reported to PDRM: {'Yes' if report_data.get('reportedToPolis') else 'No'}",
            f"Reported to BNM: {'Yes' if report_data.get('reportedToBNM') else 'No'}",
        ],
        summary=report_data.get("description", ""),
        outcome=report_data.get("status", "DRAFT — For Reference Only"),
        advice=(
            "Next Steps / Langkah Seterusnya:\n"
            "• File a police report at your nearest police station\n"
            "• Contact your bank immediately if money was transferred\n"
            "• Report to CCID: 03-2610 5000\n"
            "• Report to BNM TELELINK: 1-300-88-5465\n"
            "• Check mule accounts at: www.semakmule.rmp.gov.my\n"
            "• Report to MCMC: aduan.mcmc.gov.my"
        ),
    )

    # Build extra metadata lines for the PDF header
    extra_lines = [
        f"Report ID: {report_data.get('reportId', 'N/A')}",
        f"Incident Date: {report_data.get('incidentDate', 'N/A')}",
        f"Generated: {report_data.get('generatedAt', 'N/A')}",
    ]
    if report_data.get("victimName"):
        extra_lines.append(f"Victim Name: {report_data['victimName']}")
    if report_data.get("victimIC"):
        extra_lines.append(f"IC Number: {report_data['victimIC']}")
    if report_data.get("victimPhone"):
        extra_lines.append(f"Phone: {report_data['victimPhone']}")
    if report_data.get("bankAccount"):
        extra_lines.append(f"Scammer's Bank Account: {report_data['bankAccount']}")

    pdf_bytes = _generate_report_pdf(report, report_data.get("reportId", "N/A"), extra_lines)
    filename = f"scam-report-{report_data.get('reportId', 'export')}.pdf"

    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/report/{session_id}/pdf")
async def export_report_pdf(session_id: str):
    """
    Export the scam simulation report for a completed session as a PDF file.
    Only available once the simulation has ended (scam_ended=true).
    """
    session = _sessions.get(session_id)
    if not session:
        raise HTTPException(status_code=404, detail=f"Session '{session_id}' not found.")
    if not session.get("scam_ended"):
        raise HTTPException(status_code=400, detail="Report is only available after the simulation has ended.")
    report = session.get("report")
    if not report:
        raise HTTPException(status_code=404, detail="No report found for this session.")

    pdf_bytes = _generate_report_pdf(report, session_id)
    filename = f"scam-report-{session_id[:8]}.pdf"

    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.post("/reset", response_model=SimulatorResetResponse)
async def simulator_reset(request: SimulatorResetRequest):
    """
    Reset a simulator session to start a new scam scenario.
    """
    if request.session_id and request.session_id in _sessions:
        del _sessions[request.session_id]

    new_session_id = str(uuid.uuid4())
    return SimulatorResetResponse(
        session_id=new_session_id,
        message="Session reset. Send any message to start a new simulation.",
    )
