import React, { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

// ─────────────────────────────────────────────
// Translation strings
// ─────────────────────────────────────────────
export const translations = {
  en: {
    // Navbar
    nav_home: 'Home',
    nav_analysis: 'Analysis Bot',
    nav_simulator: 'Scam Simulator',
    nav_report: 'Report',
    nav_community: 'Community',
    nav_login: 'Login',
    nav_signup: 'Sign Up',
    nav_logout: 'Logout',
    nav_emergency: 'Emergency: 997',

    // Home
    hero_title: 'Protect Yourself from Scams',
    hero_subtitle: 'Lindungi Diri Anda dari Penipuan',
    hero_desc: 'AI-powered scam detection and education platform built for Malaysians.',
    hero_analyze: '🔍 Analyze a Message',
    hero_simulator: '🎮 Try Simulator',
    recent_scam_title: 'Recent Scam Cases',
    recent_scam_subtitle: 'Shared by the community',
    recent_scam_view_all: 'View All in Community →',
    recent_scam_empty: 'No community posts yet. Be the first to share!',

    // Analysis Bot
    analysis_title: 'Analysis Bot',
    analysis_subtitle: 'Malaysia Scam Analysis Bot',
    analysis_welcome: 'Welcome! You can:\n• Paste suspicious messages\n• Send URLs or links\n• Enter phone numbers\n• Upload screenshots\n\nI will analyze and provide a risk assessment.',
    analysis_placeholder: 'Paste suspicious message, URL, phone number...',
    analysis_analyzing: 'Analyzing...',
    analysis_risk_title: 'Risk Assessment',
    analysis_risk_subtitle: 'Scam Risk Assessment',
    analysis_indicators: 'Scam Indicators',
    analysis_no_indicators: 'No indicators detected yet. Send a message to analyze.',
    analysis_share_btn: '📢 Share to Community',
    analysis_share_tooltip: 'Risk score above 60% — share this case to warn others',

    // Simulator
    sim_title: 'Scam Simulator Coach',
    sim_subtitle: 'Scam Simulator Coach',
    sim_mode: 'SIMULATION MODE',
    sim_start: 'Start Simulation',
    sim_loading: 'Loading...',
    sim_placeholder: 'Type your response...',
    sim_tip: '💡 Tip: If you suspect a scam, say "This is a scam" or refuse to comply',
    sim_ended_success: '✅ Simulation Ended — You Succeeded!',
    sim_ended_fail: '❌ Simulation Ended — Try Again',
    sim_view_report: 'View Report',
    sim_try_again: 'Try Again',
    sim_close: 'Close',

    // Simulator report modal
    sim_report_title: '🚨 Mock Scam Report',
    sim_report_subtitle: 'Scam Simulation Report',
    sim_report_outcome_label: 'Outcome:',
    sim_report_outcome_success: '✅ SUCCESS — Scam Identified',
    sim_report_outcome_fail: '❌ FAILED — Fell for Scam',
    sim_report_pattern: '🎭 Scam Pattern Identified',
    sim_report_red_flags: '🚩 Factors That Led to Suspicion',
    sim_report_summary: '📋 Summary of Incident',
    sim_report_did_right: '🎉 What You Did Right',
    sim_report_next_time: '📚 What To Do Next Time',
    sim_report_notice_title: '⚠️ Important Notice',
    sim_report_notice_body: 'In real emergency cases, please call 997 immediately. Report scams to CCID Polis: 03-2610 5000 or BNM TELELINK: 1-300-88-5465.',

    // Community
    community_title: 'Community Scam Reports',
    community_subtitle: 'Real cases shared by Malaysians to protect each other',
    community_share: 'Share a Case',
    community_login_prompt: 'Login to share a scam case',
    community_empty: 'No cases shared yet. Be the first to warn others!',
    community_posted_by: 'Posted by',
    community_risk: 'Risk',
    community_indicators: 'Indicators',
    community_ago: 'ago',
    community_cases_shared: 'cases shared',
    community_all_posts: 'All Posts',
    community_my_posts: 'My Posts',
    community_refresh: 'Refresh',
    community_load_more: 'Load More',
    community_no_own_posts: "You haven't shared any posts yet.",
    community_extracted_msg: 'Extracted suspicious message:',
    community_suspicious_content: 'Suspicious content:',
    community_more_indicators: 'more',
    community_upvote_login: 'Login to upvote',
    community_upvote_remove: 'Remove upvote',
    community_upvote_seen: 'I have seen this scam too',
    community_seen_it: 'Seen it',
    community_seen_scam: 'Seen this scam',
    community_people_seen: 'people seen this',
    community_delete_title: 'Delete Post',
    community_delete_msg: 'Are you sure you want to delete this post? This action cannot be undone.',
    community_delete_confirm: 'Delete',
    community_delete_cancel: 'Cancel',

    // Auth
    login_title: 'Login',
    login_email: 'Email',
    login_password: 'Password',
    login_btn: 'Login',
    login_no_account: "Don't have an account?",
    login_signup_link: 'Sign up',
    signup_title: 'Create Account',
    signup_name: 'Display Name',
    signup_email: 'Email',
    signup_password: 'Password',
    signup_btn: 'Create Account',
    signup_have_account: 'Already have an account?',
    signup_login_link: 'Login',

    // Share modal
    share_title: 'Share Scam Case to Community',
    share_desc: 'Add a note (optional)',
    share_desc_placeholder: 'Describe what happened...',
    share_anonymous: 'Post anonymously',
    share_submit: 'Share to Community',
    share_cancel: 'Cancel',
    share_success: 'Successfully shared to community!',

    // Analysis Bot — tips & hints
    analysis_tip_otp: '• Never share OTP with anyone',
    analysis_tip_bank: '• Banks never call asking for passwords',
    analysis_tip_verify: '• Verify via official hotlines only',
    analysis_hotline_emergency: 'Emergency',
    analysis_enter_hint: 'Press Enter to send • Shift+Enter for new line',

    // Report Generator
    report_title: 'Report Generator',
    report_subtitle: 'Scam Incident Report Generator',
    report_notice: 'This tool generates a reference report for your records. For official police reports, please visit your nearest police station or use e-Aduan PDRM. For bank-related scams, contact your bank immediately.',
    report_incident_details: 'Incident Details',
    report_incident_date: 'Incident Date',
    report_scam_type: 'Scam Type',
    report_contact_method: 'Contact Method Used',
    report_scammer_contact: "Scammer's Contact",
    report_scammer_contact_ph: '+60123456789 or username',
    report_amount_lost: 'Amount Lost (if any)',
    report_bank_account: "Scammer's Bank Account",
    report_bank_account_ph: 'Bank name + account number',
    report_description: 'Description of Incident',
    report_description_ph: 'Describe what happened in detail...',
    report_chars: 'chars',
    report_victim_info: 'Your Information (Optional)',
    report_victim_name: 'Full Name',
    report_victim_ic: 'IC Number',
    report_victim_phone: 'Phone',
    report_reported_pdrm: 'Already reported to PDRM',
    report_reported_bnm: 'Already reported to BNM',
    report_generate_btn: 'Generate Report',
    report_reset_btn: 'Reset',
    report_new_btn: 'New Report',
    report_required: 'Required',
    report_desc_min: 'Please provide at least 20 characters',
    report_select: 'Select...',
    report_generated_label: 'Report Generated',
    report_heading: 'SCAM INCIDENT REPORT',
    report_id_label: 'Report ID',
    report_status_draft: 'DRAFT — For Reference Only',
    report_not_provided: 'Not provided',
    report_not_specified: 'Not specified',
    report_victim_section: 'Victim Information',
    report_reported_to_pdrm: 'Reported to PDRM',
    report_reported_to_bnm: 'Reported to BNM',
    report_next_steps: '🚨 Next Steps',
    report_step_police: '• File a police report at your nearest police station',
    report_step_bank: '• Contact your bank immediately if money was transferred',
    report_step_ccid: '• Report to CCID:',
    report_step_bnm: '• Report to BNM TELELINK:',
    report_step_mule: '• Check mule accounts at:',
    report_step_mcmc: '• Report to MCMC:',
    report_export_btn: 'Export PDF',
    report_exporting: 'Exporting...',
    report_export_fail: 'Failed to export PDF. Please try again.',
    report_field_date: 'Incident Date',
    report_field_type: 'Scam Type',
    report_field_contact: 'Contact Method',
    report_field_scammer: "Scammer's Contact",
    report_field_amount: 'Amount Lost',
    report_field_bank: "Scammer's Bank",
    report_field_description: 'Description',
    risk_medium: 'MEDIUM',
    risk_high: 'HIGH',
    risk_critical: 'CRITICAL',
    confidence: 'Confidence',
    tips_title: '💡 Tips',
    report_hotlines: '🚨 Report Scam',
  },

  ms: {
    // Navbar
    nav_home: 'Laman Utama',
    nav_analysis: 'Bot Analisis',
    nav_simulator: 'Simulator Penipuan',
    nav_report: 'Laporan',
    nav_community: 'Komuniti',
    nav_login: 'Log Masuk',
    nav_signup: 'Daftar',
    nav_logout: 'Log Keluar',
    nav_emergency: 'Kecemasan: 997',

    // Home
    hero_title: 'Lindungi Diri Anda dari Penipuan',
    hero_subtitle: 'Protect Yourself from Scams',
    hero_desc: 'Platform pengesanan dan pendidikan penipuan berkuasa AI untuk rakyat Malaysia.',
    hero_analyze: '🔍 Analisis Mesej',
    hero_simulator: '🎮 Cuba Simulator',
    recent_scam_title: 'Kes Penipuan Terkini',
    recent_scam_subtitle: 'Dikongsi oleh komuniti',
    recent_scam_view_all: 'Lihat Semua di Komuniti →',
    recent_scam_empty: 'Tiada siaran komuniti lagi. Jadilah yang pertama berkongsi!',

    // Analysis Bot
    analysis_title: 'Bot Analisis',
    analysis_subtitle: 'Bot Analisis Penipuan Malaysia',
    analysis_welcome: 'Selamat datang! Anda boleh:\n• Tampal mesej mencurigakan\n• Hantar URL atau pautan\n• Masukkan nombor telefon\n• Muat naik tangkapan skrin\n\nSaya akan menganalisis dan memberikan penilaian risiko.',
    analysis_placeholder: 'Tampal mesej mencurigakan, URL, nombor telefon...',
    analysis_analyzing: 'Menganalisis...',
    analysis_risk_title: 'Penilaian Risiko',
    analysis_risk_subtitle: 'Penilaian Risiko Penipuan',
    analysis_indicators: 'Petanda Penipuan',
    analysis_no_indicators: 'Tiada petanda dikesan lagi. Hantar mesej untuk dianalisis.',
    analysis_share_btn: '📢 Kongsi ke Komuniti',
    analysis_share_tooltip: 'Skor risiko melebihi 60% — kongsi kes ini untuk amaran orang lain',

    // Simulator
    sim_title: 'Jurulatih Simulator Penipuan',
    sim_subtitle: 'Jurulatih Simulator Penipuan',
    sim_mode: 'MOD SIMULASI',
    sim_start: 'Mulakan Simulasi',
    sim_loading: 'Memuatkan...',
    sim_placeholder: 'Taip respons anda...',
    sim_tip: '💡 Tip: Jika anda syak penipuan, katakan "Ini penipuan" atau enggan mematuhi',
    sim_ended_success: '✅ Simulasi Tamat — Anda Berjaya!',
    sim_ended_fail: '❌ Simulasi Tamat — Cuba Lagi',
    sim_view_report: 'Lihat Laporan',
    sim_try_again: 'Cuba Lagi',
    sim_close: 'Tutup',

    // Simulator report modal
    sim_report_title: '🚨 Laporan Penipuan Simulasi',
    sim_report_subtitle: 'Laporan Simulasi Penipuan',
    sim_report_outcome_label: 'Keputusan:',
    sim_report_outcome_success: '✅ BERJAYA — Penipuan Dikenal Pasti',
    sim_report_outcome_fail: '❌ GAGAL — Terjebak Penipuan',
    sim_report_pattern: '🎭 Corak Penipuan Dikenal Pasti',
    sim_report_red_flags: '🚩 Petanda Merah Yang Dikesan',
    sim_report_summary: '📋 Ringkasan Kejadian',
    sim_report_did_right: '🎉 Apa Yang Anda Lakukan Dengan Betul',
    sim_report_next_time: '📚 Apa Yang Perlu Dilakukan Lain Kali',
    sim_report_notice_title: '⚠️ Notis Penting',
    sim_report_notice_body: 'Dalam kes kecemasan sebenar, sila hubungi 997 dengan segera. Laporkan penipuan kepada CCID Polis: 03-2610 5000 atau BNM TELELINK: 1-300-88-5465.',

    // Community
    community_title: 'Laporan Penipuan Komuniti',
    community_subtitle: 'Kes sebenar dikongsi oleh rakyat Malaysia untuk melindungi satu sama lain',
    community_share: 'Kongsi Kes',
    community_login_prompt: 'Log masuk untuk berkongsi kes penipuan',
    community_empty: 'Tiada kes dikongsi lagi. Jadilah yang pertama memberi amaran!',
    community_posted_by: 'Dikongsi oleh',
    community_risk: 'Risiko',
    community_indicators: 'Petanda',
    community_ago: 'yang lalu',
    community_cases_shared: 'kes dikongsi',
    community_all_posts: 'Semua Siaran',
    community_my_posts: 'Siaran Saya',
    community_refresh: 'Muat Semula',
    community_load_more: 'Muatkan Lagi',
    community_no_own_posts: 'Anda belum berkongsi sebarang siaran.',
    community_extracted_msg: 'Mesej mencurigakan yang diekstrak:',
    community_suspicious_content: 'Kandungan mencurigakan:',
    community_more_indicators: 'lagi',
    community_upvote_login: 'Log masuk untuk undi',
    community_upvote_remove: 'Buang undi',
    community_upvote_seen: 'Saya pernah nampak penipuan ini juga',
    community_seen_it: 'Pernah nampak',
    community_seen_scam: 'Pernah nampak penipuan ini',
    community_people_seen: 'orang pernah nampak ini',
    community_delete_title: 'Padam Siaran',
    community_delete_msg: 'Adakah anda pasti mahu memadam siaran ini? Tindakan ini tidak boleh dibatalkan.',
    community_delete_confirm: 'Padam',
    community_delete_cancel: 'Batal',

    // Auth
    login_title: 'Log Masuk',
    login_email: 'E-mel',
    login_password: 'Kata Laluan',
    login_btn: 'Log Masuk',
    login_no_account: 'Tiada akaun?',
    login_signup_link: 'Daftar',
    signup_title: 'Buat Akaun',
    signup_name: 'Nama Paparan',
    signup_email: 'E-mel',
    signup_password: 'Kata Laluan',
    signup_btn: 'Buat Akaun',
    signup_have_account: 'Sudah ada akaun?',
    signup_login_link: 'Log Masuk',

    // Share modal
    share_title: 'Kongsi Kes Penipuan ke Komuniti',
    share_desc: 'Tambah nota (pilihan)',
    share_desc_placeholder: 'Huraikan apa yang berlaku...',
    share_anonymous: 'Siar secara tanpa nama',
    share_submit: 'Kongsi ke Komuniti',
    share_cancel: 'Batal',
    share_success: 'Berjaya dikongsi ke komuniti!',

    // Analysis Bot — tips & hints
    analysis_tip_otp: '• Jangan sekali-kali kongsi OTP dengan sesiapa',
    analysis_tip_bank: '• Bank tidak pernah telefon minta kata laluan',
    analysis_tip_verify: '• Sahkan melalui talian rasmi sahaja',
    analysis_hotline_emergency: 'Kecemasan',
    analysis_enter_hint: 'Tekan Enter untuk hantar • Shift+Enter untuk baris baru',

    // Report Generator
    report_title: 'Penjana Laporan',
    report_subtitle: 'Penjana Laporan Insiden Penipuan',
    report_notice: 'Alat ini menjana laporan rujukan untuk rekod anda. Untuk laporan polis rasmi, sila pergi ke balai polis berhampiran atau gunakan e-Aduan PDRM. Untuk penipuan berkaitan bank, hubungi bank anda dengan segera.',
    report_incident_details: 'Butiran Insiden',
    report_incident_date: 'Tarikh Insiden',
    report_scam_type: 'Jenis Penipuan',
    report_contact_method: 'Kaedah Hubungan Digunakan',
    report_scammer_contact: 'Nombor/Akaun Penipu',
    report_scammer_contact_ph: '+60123456789 atau nama pengguna',
    report_amount_lost: 'Jumlah Kerugian (jika ada)',
    report_bank_account: 'Akaun Bank Penipu',
    report_bank_account_ph: 'Nama bank + nombor akaun',
    report_description: 'Penerangan Insiden',
    report_description_ph: 'Huraikan apa yang berlaku secara terperinci...',
    report_chars: 'aksara',
    report_victim_info: 'Maklumat Anda (Pilihan)',
    report_victim_name: 'Nama Penuh',
    report_victim_ic: 'Nombor IC',
    report_victim_phone: 'Telefon',
    report_reported_pdrm: 'Sudah lapor ke PDRM',
    report_reported_bnm: 'Sudah lapor ke BNM',
    report_generate_btn: 'Jana Laporan',
    report_reset_btn: 'Set Semula',
    report_new_btn: 'Laporan Baru',
    report_required: 'Diperlukan',
    report_desc_min: 'Sila berikan sekurang-kurangnya 20 aksara',
    report_select: 'Pilih...',
    report_generated_label: 'Laporan Dijana',
    report_heading: 'LAPORAN INSIDEN PENIPUAN',
    report_id_label: 'ID Laporan',
    report_status_draft: 'DRAF — Untuk Rujukan Sahaja',
    report_not_provided: 'Tidak diberikan',
    report_not_specified: 'Tidak dinyatakan',
    report_victim_section: 'Maklumat Mangsa',
    report_reported_to_pdrm: 'Dilaporkan kepada PDRM',
    report_reported_to_bnm: 'Dilaporkan kepada BNM',
    report_next_steps: '🚨 Langkah Seterusnya',
    report_step_police: '• Buat laporan polis di balai polis berhampiran',
    report_step_bank: '• Hubungi bank anda segera jika wang telah dipindahkan',
    report_step_ccid: '• Laporkan kepada CCID:',
    report_step_bnm: '• Laporkan kepada BNM TELELINK:',
    report_step_mule: '• Semak akaun mule di:',
    report_step_mcmc: '• Laporkan kepada MCMC:',
    report_export_btn: 'Eksport PDF',
    report_exporting: 'Mengeksport...',
    report_export_fail: 'Gagal mengeksport PDF. Sila cuba lagi.',
    report_field_date: 'Tarikh Insiden',
    report_field_type: 'Jenis Penipuan',
    report_field_contact: 'Kaedah Hubungan',
    report_field_scammer: 'Hubungan Penipu',
    report_field_amount: 'Jumlah Kerugian',
    report_field_bank: 'Bank Penipu',
    report_field_description: 'Penerangan',
    risk_medium: 'SEDERHANA',
    risk_high: 'TINGGI',
    risk_critical: 'KRITIKAL',
    confidence: 'Keyakinan',
    tips_title: '💡 Petua',
    report_hotlines: '🚨 Laporkan Penipuan',
  },
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en')
  const t = (key) => translations[lang][key] ?? translations['en'][key] ?? key
  const toggleLang = () => setLang((l) => (l === 'en' ? 'ms' : 'en'))

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
