"""initial tables

Revision ID: 3f7d2724d004
Revises: 
Create Date: 2026-05-09 20:05:14.702348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f7d2724d004'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('community_posts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('scam_type', sa.String(length=100), nullable=True),
    sa.Column('image_key', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_community_posts_created_at', 'community_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_community_posts_user_id'), 'community_posts', ['user_id'], unique=False)
    op.create_table('incident_reports',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('report_id', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('incident_date', sa.String(length=20), nullable=False),
    sa.Column('scam_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('contact_method', sa.String(length=100), nullable=False),
    sa.Column('scammer_contact', sa.String(length=200), nullable=True),
    sa.Column('bank_account', sa.String(length=200), nullable=True),
    sa.Column('amount_lost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('reported_to_polis', sa.Boolean(), nullable=False),
    sa.Column('reported_to_bnm', sa.Boolean(), nullable=False),
    sa.Column('victim_name', sa.String(length=100), nullable=True),
    sa.Column('victim_ic', sa.String(length=20), nullable=True),
    sa.Column('victim_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incident_reports_created_at', 'incident_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_incident_reports_report_id'), 'incident_reports', ['report_id'], unique=True)
    op.create_index('ix_incident_reports_scam_type', 'incident_reports', ['scam_type'], unique=False)
    op.create_index(op.f('ix_incident_reports_user_id'), 'incident_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_reports_user_id'), table_name='incident_reports')
    op.drop_index('ix_incident_reports_scam_type', table_name='incident_reports')
    op.drop_index(op.f('ix_incident_reports_report_id'), table_name='incident_reports')
    op.drop_index('ix_incident_reports_created_at', table_name='incident_reports')
    op.drop_table('incident_reports')
    op.drop_index(op.f('ix_community_posts_user_id'), table_name='community_posts')
    op.drop_index('ix_community_posts_created_at', table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
