"""add community post fields

Revision ID: b7ce446361ba
Revises: 3f7d2724d004
Create Date: 2026-05-09 20:58:19.082218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ce446361ba'
down_revision: Union[str, None] = '3f7d2724d004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_posts', sa.Column('original_message', sa.Text(), nullable=True))
    op.add_column('community_posts', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('community_posts', sa.Column('risk_score', sa.Integer(), nullable=True))
    op.add_column('community_posts', sa.Column('risk_level', sa.String(length=20), nullable=True))
    op.add_column('community_posts', sa.Column('indicators', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community_posts', 'indicators')
    op.drop_column('community_posts', 'risk_level')
    op.drop_column('community_posts', 'risk_score')
    op.drop_column('community_posts', 'note')
    op.drop_column('community_posts', 'original_message')
    # ### end Alembic commands ###
