"""add post upvotes table

Revision ID: f9a2d8e4ea42
Revises: b7ce446361ba
Create Date: 2026-05-09 21:52:55.813789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9a2d8e4ea42'
down_revision: Union[str, None] = 'b7ce446361ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_upvotes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('post_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_upvote')
    )
    op.create_index('ix_post_upvotes_post_id', 'post_upvotes', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_upvotes_user_id'), 'post_upvotes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_upvotes_user_id'), table_name='post_upvotes')
    op.drop_index('ix_post_upvotes_post_id', table_name='post_upvotes')
    op.drop_table('post_upvotes')
    # ### end Alembic commands ###
